services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - PORT=${BACKEND_PORT:-8080}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8087/api}
    image: frontend:latest
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
